import "@radix-ui/themes/styles.css";
// import "./theme-config.css";
// import "./globals.css";
import "../../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import Nav from "@/components/layout/nav";
import { Suspense } from "react";
// import NavBar from "./NavBar";
// import AuthProvider from "./auth/Provider";
// import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps{
  children: React.ReactNode;
}

const IssuesRootLayout : React.FC<LayoutProps> = ({ children }) => {

  return (
    <html lang="en">
      <body className={inter.variable}>
        <Nav />
        <Theme accentColor="violet">
          <main className="p-5">
            <Container>{children}</Container>
          </main>
        </Theme>
      </body>
    </html>
  );
}

export default IssuesRootLayout;