// HERE SEEDS ARE GENERATED


/// DO NOT EDIT THIS FILE. IT IS GENERATED AUTOMATICALLY. ALL YOUR CHANGES WILL BE LOST
import { PrismaClient } from "@prisma/client"
import { now } from "next-auth/client/_utils";
const prisma = new PrismaClient();	

async function main() {
	const user = await prisma.user.create({
		data: {
			name: "John Doe",
			email: "jSb7t@example.com",
			role: "ADMIN",
			organizationId: null,
			lastLogin: new Date(),
			//createdAt: new Date(),
			//updatedAt: new Date(),

			
		},
	})
	console.log(user)
}

main()
	.then(async () => {
		await prisma.$disconnect()
	})
	.catch(async (e) => {
		console.error(e)
		await prisma.$disconnect()
		process.exit(1)
	})

