name: Update Changelog

# Triggers the workflow on push events for any branch in the repository.
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Update CHANGELOG.md
      run: |
        # Fetch all history for all tags and branches
        git fetch --prune --unshallow
        
        # Append the new logs to CHANGELOG.md
        echo "\n## [$(date +"%Y-%m-%d %H:%M:%S")] - Changes made by $GITHUB_ACTOR" >> CHANGELOG.md
        git log -1 --pretty=format:'%h - %s' >> CHANGELOG.md
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "jdaly2991@gmail.com"
        git config --global user.name "artistatbl"
        git add CHANGELOG.md
        # Only proceed if there's a change to commit
        git diff --staged --quiet || git commit -m "Update CHANGELOG.md"
        git push --set-upstream https://${{secrets.PERSONAL_TOKEN}}@github.com/artistatbl/Bugify.git main

